language: ruby
rvm:
  - 2.2.1
script:
  - gem install html-proofer
  - ruby -S bundle install
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html --empty-alt-ignore --allow-hash-href --file-ignore ./_site/contrib/donna/donna.html
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
