# Site settings
title: Rough Linen
email: felix@roughlinen.com
description: > # Rough Linen - real, natural linen, the way it used to be
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://roughlinen.com" # the base hostname & protocol for your site
twitter_username: roughlinen
github_username:  fsargent

collections:
  contrib:
    output: true
permalink: /contrib/:title/:title.html

# Build settings
markdown: kramdown
include: [.htaccess]
detatch: true
gems:
  - jekyll-sitemap
